þX	þYYþXXX	[XWþZ
Y	Z
[	VþZ
ZZZY
[Z	þ][[
Y	[[\[\þ^[[ZZ\][
óþ	[[[[\]\
êé	þ
^^\[\\\]ê	êXþ]^\\[\\]ëê
ö
þ
^^\\\\]\öëêêþ\[\[\]\]ììíëëììþ][\	Z\\\\YY]îííþ[]\][]
[[[[Z[ZZîîíþY[\]]]\[[Z[[\[[[Z[\\^þZZ[[\]]][[\]]]]]ZYZ\\þ\\\]]]][Z]]]]]]\]]\]\þ\]]]]^]\\ZZ[\[Z[\]]\þ\]][\][[[Z

[[Z[Z]]]\þ\[\[]^[\\[[[Z[[[[]]\þ]\\[\]]\
I]]\\\Z\þ\\\[]]\
JKK\]\þ\\]\^^VùKKI]]\þ\\]^J	LLK^[\ZþZ\]]_KKMKKL^
þ
[]]^KKLML^\[ºþ¼\½½\\þ\
\»\\\½»
ZþZº]]í]í\
Y
[
þ[[Z[
YY
¼[í]]]\[ZY
ZZ
Yþ[»Z[Z
[Z[»[»[
º
YZêYêþ[»ZY[
[Z[
[Z[º
ºþ[»[»»[»»ÿþUþXXYXXWVþWZ[[
YZXVVþWXW
Y	[[
ZXUþWXZY	WYZ[\[YþHY	XWY		[[WXY	WþFHWXXWY[YY[YþD6öHVYZ[\\ZZY
[YUþ3uvFHXY\öëëZYZ[	Vþ3†uóö
êêöëëë[[[YWTþFÕtÕê
é
êìíìì\ZXUþCÕtVÕtç		^íìíø[YVþ3ÕèVÕÆÕë
íìí
Zþ3ÕÆVÕÕÕ¼
îìëíZZWþ3…ÕVÕÆÇøøúìì¾[
XVþEtÆÕÕ…çøëííìëîí[ZXVþE3s×ÆÕ†vúìëíîí\][Yþ3FÕÆÕÆ…éúììí\\]]ZYVþB33ÆÆÅÆÕÕçîî]\]]\[YWþ333ÖÆ„ÅÆÕçH]^]\]\\\X	þ3F†ÕÆVæÕÕYH]]]\[\\[Vþ3ÖÕòÆV3†…FH]]]]\\[XXþ2Õ33ÖVBu†FH]]][[[[	Yþu‡A3ÕVVõÕFH\]ZZZ[]XYþÕ†óÕÕÆV†ÕFH\Z\[[þÕó6Õ×å3ÕÕFH\\[XþÕó33Õ´2ÕÕ[\]
ZþÕó3DÖt3éÕH[[ú§[Xþ‡‡D3†v3
Õº[\gZþFF33DFHì»\]f	WþFFFH¼\[[Zi™WþH
Z[¹§(þ»ö»Y	ºþZ
	¹þ
ÿþUþUVVZ[þXWWYY\þWXX]]þWYX]]küþYZX\\ü™jœ_ZYþY[YX[Z^^^]ZYKþY[Y	XXXY[\\
Y‹‰þY
	Y\Z	XXYY\
ù×‰þ
X	]ZZ		[Z=Õ‰‰þWS
[^\[Z[[KŠ××‰þ[	Xû
][]K…Ö×KþXU	Z	X	S	äÂÔÂƒÖ‰þ
[[[YX
UäÕÂ×Ôäå‰þ
YYYZZ
[ãÓÕÕÕÄã‰þY	YYZ[[[Z[	WâÁÄÆÃÕ„ôþYY	Y
Z[[[[ZÕÕÁÃÕ××ÔõþXZYYZZZZ[\\çÕÕ„Õ×ÕÔ8þXYV·Z[[
Z\Z[JÃÄÓÄÂÄÕyþWø¹·Z»[\Z[KJ7ðsu89×‰þ
^ú¹¹\\\ZZKzÕvH::UØÕþWºº»\]\[K‰×tô::V:×þZºZ¼[[\[\\K‰×ÅF:9VøÖþXY
[\\\[[[ZK××æ÷:
ñŠ‰þX[Z[\\[[[Z[K×‰æ‰ÖòõÖ‰þ	Z[\[Z[[[[K××Ä×Õæ9Ö:þY
ZZZZ[\\K××çéÕÅ:ÕŠþY[Z
Z[\]]Š‰9ˆ‡:Õ;þY[[[[[\\[ù×:÷Ö×ÖùJþgøZ

[
[ØJ‰×øùKKþf\î[½[[KJ‰×KKþh¦¸¼\»\K×zþ»¦¦™½\\]ÉÕþºYZ]í]þ[öZYYÿ
þ
TUUTTRTUUVWþVTUUTTRTUUVWXYYþH[YYUWXY	Z
YYYðþHGJKßüú[XVW
KKþHFG_üÙÛüü^WLKJJKJþ
HFEüÙÛûZŠŠK::JJIþHFD6LüÚ×Ù×üŠŠü:Š9JŠþ7F4Ö_üÞÙ××ü>‰×::JJþHFDóÖüØ×Û×ÛüL‰Ö:::ŠJþHFD…ÖÝÛÙÛÛÛü<tè:::JKþHFDU‡\ÝÛÛÛ×ÛŽüIvæ×:‰‰<þHFD3†5Ø×ÛÛ×ÛÚû=:‰æ×::×‰KþHFD2VÕ3Ö×ÛÛÙÙÚü=J:‰ÅwJ::×KþHFDÖ3Õ××Û×‰ü>:H::‰…t:::×KþHFCðòÕÕÕÕtôÕ4H::‰:::‰Õç:::ÖKþHFV2óÕòÕÄÕò3ÖòH:Š×Ö::‰ÕÅ9H:×KþHVV33Õ††ÄÕ3ÕñHH:‰×::‰ÕÆÖ::‰KþHDD3Õt†ÄÕ†3††H::ŠÖ::Ø×…è::JKþHFDóÕt†ÄÕÕ3t…H:::Ö::JÕw´9JKþHFDtÕt†ÅÖ†Õ†ÕH::‰×Š×:×‰çwJKþHFD†Ö3Å…Õ3Õt†H:J÷Ö:Õ×::××JKþHFu†3å†ÕB†tDH::‰×:Ø×::Ö‰Kþ[H‡ô2åó33†‡3H::;Ö:;ÖH:Ö;Kþ[[H‡õV…333t†3H::ø×::Ö;:Õû[[[þ[Ö÷UÕ	33u†FHH:‰×:H::<L[[þ
[GFFDD††BH::::::JJK[þHHFFuu3H::::JJKKþHH6ÕDD::JJKKþH×‡FJJKKþˆHKJÿþkþZZ	þZY
[YZZþ[
YY\
Y
[þ\
YY[[[\\þ]Z	Y\]\þ^ZY[\]\]öþú\Z[[\[
ëöêþ^[\\\[÷
ëþ^ú][[\\[[[
ëþ
^[\\[[\
Y
ìþ



\\\\[ZXX\
þ]]]]^\\\\\\[
Z[þ\\]][[[
\\[\[\\þ[\\\]]]\\
ZZ[\\\\\\þ
[[\]]\\\\\]]\\\]\þ\\\\][[]]]]]\\[]]þ\]]]\\[[[Y[[[[\\\[]]\þ\][Z[YZYYZ[[[[[\]]\þ]\\\\ZZ[[[[Z[[[[\]][þ]\]\[[[\[[þ]]\\\]I\\[[]\þ\]\]
K\]þ]\\K^^^\^^\]\þ[]\]^^^^[þ[^^^^K^KK]][
þ\]^^_^^\½]þZí\[\]]ëY
þY\
[½]]»
Y	¸êYþ[[
Z	¸èYëZ\í\»º	éYY
Z[þ»[»
YYY
¹

º
êYY	¹Y
»
»þ[»ëéY	
¹
YY
º
[
»[þT[»[ºö[»»[TTÿþVWYþWXX]]XþXY	\þYYZX^þX	X[gþ[	Y[[
^i‰þY[Z[[YX[^]^]‹‰þ
öY
[

[Z[[\ù×‰þT[
X\\[
\\=Õ‰‰þVU	V[^]]K‰××KþWTEG	^ú^K…Ö×‰þ	ZYZäÂÔÂÄÖ‰þ
[[\	]VñÕÂ×Ôpq‰þ[[
\[[ñöãÓÕÕÕÄãþ[[Z[\\\]^âÁÄÆÃÕ„ôþY[[

[[

…ÕÁÃÕ××ÔõþW	[[[[Z
[[\èÕÕ„Õ×ÕÔ8þYX	º[[ZYZ[[äÄÓÄÂÄÕyþXYXX
[[ZY;Jõñsu8òÕ‰þ	ºYV
ºY»[[ùŠÕçJ::VwÕþW[Y
úºZ\\[‹‰†ç:Š:U:×þXºº»Z\\\Š‰èÆ÷:÷øÖþX
ZZºZ½Z[[[Š×‡æ9Š;V÷‰þX[Z[\\[[[\y×‰ÅèÖØ†‰þY
[[\\\\ŠØ×ÕæÕ×ôÅ:þY[\]Šˆ××÷Öy9æõþ[]]]‰‰:‰×J:Õ9þ¦[\]\]Š×:÷Ö×Ö<Jþ¥ú^


\[ØJ‰ÖøùKKþg^]»
½[\<J‰ØKKþ¦Y
»[\\K×‹þ»¦(§ë[ë¼]
Õþ[êXYö»þ[
Y¸	ÿþYXYXþVZ[ZZYYþYXY
Y[
ZWþXXZYWYZ[\[Wþ[	XóY	XWX	Y[þHH	ZWXYW	[[YYþF6Y[XWWY[ZZ\\Z[ZþDuöHXX
]\[ZY
[YVþ3†vFHZYZö\ùùù[
[[YTþ3Õuóö
\ììêöíú]ZþFÕtÕê÷ì
		ëøîù[YVþCÕtVÕtç
éöìîî[
Wþ3ÕèVÕÆÕçê	
ìîúú
ZWþ3ÕVVÕÕÕÆöëëíúú[ZXVþ3…VÆÕÆÇÕÕëøî\[
XVþEtÆÕÕ…çÕèìî»][YWþE3s×ÆÕ†vçí
[ö\[
\]ZYVþ3FÕÆÕÆ…évZ
[\\\\[
VþB33Æ…ÅÆÕÕç[[[]\\]\\Wþ333ÖÕ„VÆÕçH\]][]\\[Uþ33†ÕÕÅVÕÕYH\\[[[Xþ33ÕòæVV†…FH\[\\[\\	þ2233ÖVÆu†FH\]\Z[[\XþuuA3ÕV3õÕFH\\
ZZZ[XþÕÕóÕVV3†ÕFH[[Z[[
[XþÕÕ6VVå3ÕÕFH\\ø
YþÕÕÆVÆ´2ÕÕZ\][XþÕÕVVÖt3éÕH]
Wþ‡‡D3†v3
Õº[[]§XWþFF33DFH»^ú˜WþFFFH¼



Y¹¥VþH
[
	ºY¹¹™Tþ
êº
	Z[TþY
º[þ[ÿ
þ	TUTTTTTTTUUþVTUUSTRTVUVW	YYWþHYUVVWUX	Y
ZY	YðþHGJ	XXVVVXYXWKKþHFG_üÙÛZXWWWLKJJKJþ
HFEüÙÛZYLüÛK::JŠJþHFD6üÛÚüLLü×:Š:JJþHF	Ö_NüÞØ×ÛLüÛ>‰×9:ŠJþHFŠóÖüØÛÛüûÛ×L‰×:::JJþHFDsÖÝ×Û×Ûü?ÛÛ<‰‰:::ŠJþHFCð‡\Ý×ÛÛÞKÛÛHç†×:‰×<þHFDðç†5Ø×Û?ÛÛ=:èÆ×;:×‰KþHFDVð‡3Ö××Ù_=J:v„×J::×KþHFDòÕ3Õ××ˆ×‰üü>:H::vÅ×:::×KþHFDUóÕòÕ×ÕtôÕ4H::‰:::v…Õ:::ÖKþHFDU4ÕóÕÄÕt3ÖòH:Š×Ö::uÆ×ŠH:×{þHFDUòÕ…ÖÄÕ3ÕñHH:‰×::è„××::‰<þHFDUÕ†…ÅÕ†3††H::ŠÕ×:ÆÕ××‰ŠJKþHFUòÕt…ÅÕÖ3t…H::ŠÕ×:VÕ‰×‰J>þHFVñÕt†ÅÖ†Õ†ÕH:::Ö×ÖVÖŠÖ×JKþHFCðÖ3ÕÄÕ3Õt†H:J÷Õ×Åt;:Ö×JKþHFææ2ÕæÕB†…DH::‰×ÖèÖ:;Õ×Jþ[H‡ó3ÕV2tÕÖ3H::Š×ÖùÖHŠÕØJþ[[H‡õDÕñV3ÕÕ3H::;ÖÕŠÖ;:ÕŒ[HHþ[×÷FÕóUð†ÕFHH:‰××::J>[[þ
HFFD¡ÕÕBH:::ŠÖ:JJK»þHHFFuu3H::::×;KKþHH
ÕXH::JJKKþH×‡FJJKKþˆHKKÿ